<?xml version="1.0"?>

   <robot xmlns:xacro="http://wiki.ros.org/xacro" name="ur5_arm1">
  <xacro:property name="arm2_pedestal_base_height" value="0.85"/>
  
  <xacro:property name="bracket_x" value="0.075"/>
  <xacro:property name="bracket_y" value="0.075"/>
  <xacro:property name="bracket_z" value="0.008"/>
  
  <xacro:property name="realsense_d435i_x" value="0.09"/>
  <xacro:property name="realsense_d435i_y" value="0.025"/>
  <xacro:property name="realsense_d435i_z" value="0.025"/>
  
  <xacro:property name="realsense_d435i_depth_lens_y_offset" value="0.0175"/>
  <xacro:property name="realsense_d435i_depth_lens_z_offset" value="0.0042"/>
  
  <xacro:property name="realsense_d435i_colour_lens_y_offset" value="0.0325"/>

  <link name="arm2_pedestal">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 ${arm2_pedestal_base_height/2}"/>
      <mass value="20"/>
      <inertia ixx="200" ixy="200" ixz="200" iyy="200" iyz="200" izz="200"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://ur5_control/meshes/robot2_pedestal.dae"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://ur5_control/meshes/robot2_pedestal.dae"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="arm2_pedestal_joint" type="fixed">
    <parent link="arm2_pedestal" />
    <child link="arm2_base_link" />
    <origin xyz="0 0 ${arm2_pedestal_base_height}" rpy="0.0 0.0 0.0"/>
  </joint>

  <link name="arm2_tool0_controller"/>
  <joint name="arm2_tool_controller_fake_joint" type="fixed">
    <parent link="arm2_tool0"/>
    <child link="arm2_tool0_controller"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>
  
  <link name="arm2_bracket">
    <inertial>
      <mass value="1" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://ur5_control/meshes/ur5_realsense_bracket_and_usb_cable.dae"/>
      </geometry>
      <material name="Blue">
        <color rgba="0.1 0.1 0.7 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://ur5_control/meshes/ur5_realsense_bracket_and_usb_cable.dae"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="arm2_bracket_joint" type="fixed">
    <axis xyz="0 0 1" />
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="arm2_tool0_controller"/>
    <child link="arm2_bracket"/>
  </joint> 	
  
  <link name="arm2_camera_obj">
    <inertial>
      <mass value="1" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${realsense_d435i_y} ${realsense_d435i_x} ${realsense_d435i_z}"/>
      </geometry>
      <material name="Silver">
        <color rgba="0.75 0.75 0.75 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${realsense_d435i_y} ${realsense_d435i_x} ${realsense_d435i_z}"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="arm2_camera_joint" type="fixed">
    <axis xyz="0 0 1" />
    <origin xyz="0 0 ${realsense_d435i_y/2 + bracket_z}" rpy="0 -${pi/2} -${pi/2}"/>
    <parent link="arm2_bracket"/>
    <child link="arm2_camera_obj"/>
  </joint>
  
  <link name="arm2_camera_link"/>
  
  <joint name="arm2_lens_joint" type="fixed">
    <axis xyz="0 0 1" />
    <origin xyz="${realsense_d435i_depth_lens_z_offset} ${realsense_d435i_depth_lens_y_offset} 0" rpy="0 0 0"/>
    <parent link="arm2_camera_obj"/>
    <child link="arm2_camera_link"/>
  </joint>
  
  <link name="arm2_camera_controller"/>
  
  <joint name="arm2_camera_controller_joint" type="fixed"> 
    <axis xyz="0 0 1" /> 
    <origin xyz="0.03425 0.00625 0.024402308559790253" rpy="-0.0278 0.019 0.0"/> 
    <!-- OLD: xyz="0.03222713705152273 0.00027543478063308223 0.024402308559790253" rpy="0.005 -0.0024  0.0032" rpy="0.0 0.01 0.0" -->
    <parent link="arm2_tool0_controller"/>
    <child link="arm2_camera_controller"/>
  </joint>
  
  <link name="arm2_camera_predicted_colour_lens"/>
  
  <joint name="arm2_predicted_lens_joint" type="fixed">
    <axis xyz="0 0 1" />
    <origin xyz="${0.024402308559790253-realsense_d435i_z+realsense_d435i_depth_lens_z_offset} 0.03425 0.00625" rpy="0.0 -0.0278 0.019"/>
    <parent link="arm2_camera_obj"/>
    <child link="arm2_camera_predicted_colour_lens"/>
  </joint>
  
  </robot>

