controller_list:
- name: "arm1/arm1_scaled_pos_joint_traj_controller"
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  joints:
    - arm1_shoulder_pan_joint
    - arm1_shoulder_lift_joint
    - arm1_elbow_joint
    - arm1_wrist_1_joint
    - arm1_wrist_2_joint
    - arm1_wrist_3_joint      
- name: "arm2/arm2_scaled_pos_joint_traj_controller"
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  joints:
    - arm2_shoulder_pan_joint
    - arm2_shoulder_lift_joint
    - arm2_elbow_joint
    - arm2_wrist_1_joint
    - arm2_wrist_2_joint
    - arm2_wrist_3_joint
