<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="$(arg robot_model)_robot">

  <xacro:include filename="$(find ur_gazebo)/urdf/ur_macro.xacro"/>

  <xacro:arg name="joint_limit_params" default=""/>
  <xacro:arg name="physical_params" default=""/>
  <xacro:arg name="kinematics_params" default=""/>
  <xacro:arg name="visual_params" default=""/>

  <xacro:arg name="transmission_hw_interface" default="hardware_interface/EffortJointInterface"/>
  <xacro:arg name="safety_limits" default="false"/>
  <xacro:arg name="safety_pos_margin" default="0.15"/>
  <xacro:arg name="safety_k_position" default="20"/>

  <xacro:ur_robot_gazebo
    prefix=""
    joint_limits_parameters_file="$(arg joint_limit_params)"
    kinematics_parameters_file="$(arg kinematics_params)"
    physical_parameters_file="$(arg physical_params)"
    visual_parameters_file="$(arg visual_params)"
    transmission_hw_interface="$(arg transmission_hw_interface)"
    safety_limits="$(arg safety_limits)"
    safety_pos_margin="$(arg safety_pos_margin)"
    safety_k_position="$(arg safety_k_position)"
  />
  
  <xacro:property name="pedestal_base_height" value="0.845"/>
  
  <link name="world"/>
  
  <link name="pedestal">
    <inertial>
      <origin xyz="0 0 ${pedestal_base_height/2}" rpy="0 0 0"/>
      <mass value="20"/>
      <inertia ixx="200" ixy="200" ixz="200" iyy="200" iyz="200" izz="200"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://ur5_control/meshes/b75_pedestal.dae"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://ur5_control/meshes/b75_pedestal.dae"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="world_joint" type="fixed">
    <parent link="world" />
    <child link="pedestal" />
    <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
  </joint>

  <joint name="base_joint" type="fixed">
    <parent link="pedestal" />
    <child link="base_link" />
    <origin xyz="0 0 ${pedestal_base_height}" rpy="0.0 0.0 0.0"/>
  </joint>

  <link name="tool0_controller"/>
  <joint name="tool_controller_fake_joint" type="fixed">
    <parent link="tool0"/>
    <child link="tool0_controller"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>
  
  <xacro:property name="bracket_x" value="0.075"/>
  <xacro:property name="bracket_y" value="0.075"/>
  <xacro:property name="bracket_z" value="0.008"/>
  
  <xacro:property name="realsense_d435i_x" value="0.09"/>
  <xacro:property name="realsense_d435i_y" value="0.025"/>
  <xacro:property name="realsense_d435i_z" value="0.025"/>
  
  <xacro:property name="realsense_d435i_hov" value="69"/>
  <xacro:property name="realsense_d435i_fps" value="30.0"/>
  
  <xacro:property name="realsense_d435i_img_width" value="800"/>
  <xacro:property name="realsense_d435i_img_height" value="800"/>
 
  
  <link name="bracket">
    <inertial>
      <mass value="1" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://ur5_control/meshes/ur5_realsense_bracket_and_usb_cable.dae"/>
      </geometry>
      <material name="Blue">
        <color rgba="0.1 0.1 0.7 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://ur5_control/meshes/ur5_realsense_bracket_and_usb_cable.dae"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="bracket_joint" type="fixed">
    <axis xyz="0 0 1" />
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="tool0_controller"/>
    <child link="bracket"/>
  </joint>
  
  <!-- Camera -->
  <link name="camera_link">
    <inertial>
      <mass value="1" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${realsense_d435i_y} ${realsense_d435i_x} ${realsense_d435i_z}"/>
      </geometry>
      <material name="Silver">
        <color rgba="0.75 0.75 0.75 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${realsense_d435i_y} ${realsense_d435i_x} ${realsense_d435i_z}"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="camera_joint" type="fixed">
    <axis xyz="0 0 1" />
    <origin xyz="0 0 ${realsense_d435i_y/2 + bracket_z}" rpy="0 -${pi/2} -${pi/2}"/>
    <parent link="bracket"/>
    <child link="camera_link"/>
  </joint>
  
  <gazebo reference="camera_link">
    <sensor type="camera" name="camera">
      <update_rate>${realsense_d435i_fps}</update_rate>
      <visualize>true</visualize>
      <camera name="head">
        <horizontal_fov>${(pi/180) * realsense_d435i_hov}</horizontal_fov>
        <image> 
          <width>${realsense_d435i_img_width}</width>
          <height>${realsense_d435i_img_height}</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>500</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <!-- Noise is sampled independently per pixel on each frame.
               That pixel's noise value is added to each of its color
               channels, which at that point lie in the range [0,1]. -->
          <mean>0.0</mean>
          <stddev>0.000</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>camera/color</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera_link</frameName>
        <hackBaseline>0.07</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
  </gazebo>
  
</robot>
