controller_list:
- name: "arm1_scaled_pos_joint_traj_controller"
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  joints:
    - arm1_shoulder_pan_joint
    - arm1_shoulder_lift_joint
    - arm1_elbow_joint
    - arm1_wrist_1_joint
    - arm1_wrist_2_joint
    - arm1_wrist_3_joint
